#!/usr/bin/env bash

------------------------------------------------------------------------------------------------
# refer to man pages for "/proc/stat", to know about the attributes and naming convention
#/proc/stat
#              kernel/system statistics.  Varies with architecture.  Common
#              entries
------------------------------------------------------------------------------------------------

read_proc() {
  echo "Read"
}

read_proc
