#!/usr/bin/env bash

#------------------------------------------------------------------------------------------------
# refer to man pages for "/proc/stat", to know about the attributes and naming convention
#/proc/stat
#              kernel/system statistics.  Varies with architecture.  Common
#              entries
#------------------------------------------------------------------------------------------------

read_proc() {

  #------------------------------------------------------------------------------------------------
  local busy_time idle_time val_pair
  #------------------------------------------------------------------------------------------------
  local key user nice system idle iowait
  local irq softirq steal guest guest_nice
  while read -r key user nice system idle iowait \
    irq softirq steal guest guest_nice; do

    if [[ $key != cpu* ]]; then
      break
    fi

    busy_time=$((user + nice + system + irq + softirq + steal + guest + guest_nice))
    idle_time=$((idle + iowait))
    val_pair="$busy_time $idle_time"
    echo -e "$key - user:$user - \n|-Busy Time: $busy_time\n|-Idle Time:$idle_time\n"
  done </proc/stat
}

read_proc
